FROM golang:1.25 as go
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOBIN=/bin

FROM go as build
ARG TARGETPLATFORM
ARG TARGETARCH
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -mod=vendor -a -o /bin/app .

FROM registry.access.redhat.com/ubi10/ubi-minimal as runtime

RUN mkdir -p /licenses
COPY LICENSE /licenses/

COPY --from=build /bin/app /bin/app

USER 65534

ENTRYPOINT ["/bin/app"]
